# MediaPipe(端末内の AI)は CocoaPods で配られている
platform :ios, '17.0'
project 'StudyApp.xcodeproj'

target 'StudyApp' do
  use_frameworks!
  pod 'MediaPipeTasksVision', '~> 0.10'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
